### PR TITLE
Version 4.0.0 !

### PR DESCRIPTION
**Pull request by jimmydorry**
Push all the new stuff to master

### CODE REVIEW

**Comment by jimmydorry** [comment]
@Crazy-Duck @howardchung Let's see what Travis does!

**Comment by Crazy-Duck** [comment]
Kreygasm

**Comment by jimmydorry** [comment]
It worked!

**Comment by jimmydorry** [comment]
Kreygasm

**Comment by jimmydorry** [comment]
Shall we push the big merge button, or are we waiting for anything else big? If we merge, we can then shout at rjackson to release. Clicka Clicka Clicka

**Comment by Crazy-Duck** [comment]
I've got nothing big coming in any case. I might look into adding a few test over the coming weeks, but no need to wait for that. I think it's more important we've got a working version out again, cause the current master is pretty broken what with all the proto changes... @howardchung what do you think?

**Comment by howardchung** [comment]
You guys use this much more heavily than I do.  As long as requestMatchDetails, requestPlayerProfileCard, and requestMatchmakingStats works, I'm happy

**Comment by Crazy-Duck** [comment]
I think yasp is by far the biggest client of this lib in terms of userbase I think, so can't hurt to ask :) wouldn't want my beloved stat site to suffer ^^

**Comment by jimmydorry** [comment]
Hope they work then. :fire:

**Comment by Crazy-Duck** [comment]
since two out of those three now have travis tests, I'd say they do :laughing:

**Comment by jimmydorry** [comment]
@RJacksonm1 push this sucker to npm

**Comment by Crazy-Duck** [comment]
hold it, I've taken a quick look at requestMatchMakingStats and it seems the proto for that one has changed. Due to this change the first two parameters that were returned in the event do no longer exist D: New protobuf
```
message CMsgDOTAMatchmakingStatsResponse {
	optional uint32 matchgroups_version = 1;
	repeated uint32 legacy_searching_players_by_group_source2 = 7;
	repeated .CMsgMatchmakingMatchGroupInfo match_groups = 8;
}
```
@howardchung how do you prefer we proceed? 
* nuke the first two parameters so the entire response object is the only parameter left
* replace the first two with matchgroups_version (which is null currently) and match_groups, third stays the same
* do nothing
* ...

**Comment by jimmydorry** [comment]
... :+1:

**Comment by Crazy-Duck** [comment]
Serves us right for not having more extensive tests I guess -_- I'll look into improving this over the course of the following days / weeks

**Comment by howardchung** [comment]
@albertcui wrote the code for MMstats.  He's traveling until August, though.

I probably won't be updating the node-dota2 dependency anyway, so you can change the API if you want.

**Comment by Crazy-Duck** [comment]
Is it still working though? Cause the proto changed quite drastically 

On 31 May 2016 6:16 p.m., Howard Chung <notifications@github.com> wrote:

@albertcui wrote the code for MMstats. He's traveling until August, though.

I probably won't be updating the node-dota2 dependency anyway, so you can change the API if you want.

**Comment by howardchung** [comment]
https://github.com/yasp-dota/yasp/blob/master/package.json

We are using 3.0.0 and I believe it's working.

https://yasp.co/mmstats

**Pull request merged**
