### PR TITLE
Test #284

### PR DESCRIPTION
**Pull request by jimmydorry**
See what #284 does

### CODE REVIEW

**Comment by jimmydorry** [comment]
@Crazy-Duck @howardchung seems like the long way of doing things... as a failure would mean reverting dev branch

**Comment by Crazy-Duck** [comment]
Whether you create a different branch for pull requests and make PR's into dev or make a staging branch to which you pull from dev, both kinda have the same problem of having to revert the branch :/

**Comment by Crazy-Duck** [comment]
Ideally we'd need a system where we can approve a PR for testing, see if tests pass and then pull. That way we wouldn't need to revert. I've got no clue however if github/travis support such a model..

**Comment by jimmydorry** [comment]
If I PR into dev, I can close without merging... or comment without merging.

This is a lot of hassle considering that accounts are free and easy to create and hi-jacking the account loses us very little.

**Comment by Crazy-Duck** [comment]
I'm not opposed to the idea, go with whatever works best for you :)

**Comment by jimmydorry** [comment]
We'll get rjackson to colab you and howard (so you remain unchanged), but I'll ask others to PR the new staging branch. I think that works the easiest.

**Comment by Crazy-Duck** [comment]
Works for me :)

**Comment by howardchung** [comment]
If you really don't care about the account, you can hardcode the credentials into the test.

**Pull request merged**
