### PR TITLE
Version 1.0.0

### PR DESCRIPTION
**Pull request by RJacksonm1**
PR to discuss the progress of version 1.0.0.  A continuation from #96 and #90

### CODE REVIEW

**Comment by jimmydorry** [comment]
Unconfirmed bug https://github.com/RJacksonm1/node-dota2/issues/105

**Comment by howardchung** [comment]
parties are still commented out:
https://github.com/RJacksonm1/node-dota2/blob/1.0.0-dev/index.js#L216

@Crazy-Duck, did you fix those methods or not?

**Comment by howardchung** [comment]
looks like: they work, but messages.js is missing the appropriate enums from here:
https://github.com/SteamDatabase/GameTracking/blob/809e15e31bd491f5008b23ec15ff57865b74efb4/Protobufs/dota/base_gcmessages.proto#L6

**Comment by anar4you** [comment]
Error: Cannot find module './messages'

**Comment by howardchung** [comment]
fixed in https://github.com/RJacksonm1/node-dota2/pull/116

**Comment by anar4you** [comment]
handlers[Dota2.schema.EGCBaseClientMsg.k_EMsgGCClientWelcome] = function clientWelcomeHandler(message) {
                                      ^

TypeError: Cannot read property 'k_EMsgGCClientWelcome' of undefined
    at Object.<anonymous> (C:\Users\anar4\Desktop\steam\index.js:168:39)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\anar4\Desktop\steam\test\test.js:5:13)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

**Comment by howardchung** [comment]
I think that is also fixed in #116.  @Crazy-Duck can confirm

**Comment by anar4you** [comment]
C:\Users\anar4\Desktop\steam\test>node test.js
4 Oct 15:28:01 - Logged on.
4 Oct 15:28:01 - Launching Dota 2
4 Oct 15:28:01 - Received servers.
4 Oct 15:28:01 - sentryfile saved
4 Oct 15:28:02 - Sending ClientHello
4 Oct 15:28:03 - GC Connection Status unreliable - 3
4 Oct 15:28:03 - UNHANDLED MESSAGE 7388
4 Oct 15:28:04 - Received client welcome.
Node-dota2 ready.
C:\Users\anar4\Desktop\steam\test\test.js:41
      Dota2.matchDetailsRequest(246546269, function(err, body) {
            ^

TypeError: Dota2.matchDetailsRequest is not a function
    at Dota2Client.<anonymous> (C:\Users\anar4\Desktop\steam\test\test.js:41:13)
    at emitNone (events.js:67:13)
    at Dota2Client.emit (events.js:166:7)
    at Dota2Client.clientWelcomeHandler (C:\Users\anar4\Desktop\steam\index.js:182:8)
    at SteamGameCoordinator.fromGC (C:\Users\anar4\Desktop\steam\index.js:73:30)
    at emitThree (events.js:97:13)
    at SteamGameCoordinator.emit (events.js:175:7)
    at SteamGameCoordinator.handlers.(anonymous function) (C:\Users\anar4\Desktop\steam\node_modules\steam\lib\handlers\game_coordinator\index.js:107:10)
    at SteamGameCoordinator.<anonymous> (C:\Users\anar4\Desktop\steam\node_modules\steam\lib\handlers\game_coordinator\index.js:19:28)
    at emitThree (events.js:102:20)

**Comment by howardchung** [comment]
I think the method was renamed requestMatchDetails.  Again, @Crazy-Duck can confirm.  The README is not updated for 1.0.0

**Comment by anar4you** [comment]
C:\Users\anar4\Desktop\steam\test>node test.js
5 Oct 02:22:07 - Logged on.
5 Oct 02:22:07 - Launching Dota 2
5 Oct 02:22:07 - Received servers.
5 Oct 02:22:08 - Sending ClientHello
5 Oct 02:22:09 - Received client welcome.
Node-dota2 ready.
5 Oct 02:22:09 - Joining chat channel: Anar4youChannel
5 Oct 02:22:09 - Sending match CMsgPracticeLobbyCreate request
5 Oct 02:22:09 - Cache subscribed, type 7
5 Oct 02:22:09 - Unknown cache ID: 7
5 Oct 02:22:09 - Chat channel Anar4youChannel has 0 person(s) online
5 Oct 02:22:09 - Received create/flip/shuffle/kick/launch/leave response {"result":2}
C:\Users\anar4\Desktop\steam\handlers\lobbies.js:310
  if(callback) callback(practiceLobbyResponse.result, practiceLobbyResponse);
               ^

TypeError: callback is not a function
    at Dota2Client.onPracticeLobbyResponse (C:\Users\anar4\Desktop\steam\handlers\lobbies.js:310:16)
    at Object.<anonymous> (C:\Users\anar4\Desktop\steam\handlers\lobbies.js:62:43)
    at SteamGameCoordinator.handlers.(anonymous function) (C:\Users\anar4\Desktop\steam\node_modules\steam\lib\handlers\game_coordinator\index.js:105:28)
    at SteamGameCoordinator.<anonymous> (C:\Users\anar4\Desktop\steam\node_modules\steam\lib\handlers\game_coordinator\index.js:19:28)
    at emitThree (events.js:102:20)
    at SteamClient.emit (events.js:175:7)
    at SteamClient._netMsgReceived (C:\Users\anar4\Desktop\steam\node_modules\steam\lib\steam_client.js:172:10)
    at SteamClient.handlers.(anonymous function) (C:\Users\anar4\Desktop\steam\node_modules\steam\lib\steam_client.js:259:10)
    at SteamClient._netMsgReceived (C:\Users\anar4\Desktop\steam\node_modules\steam\lib\steam_client.js:157:26)
    at emitOne (events.js:77:13)

**Comment by Crazy-Duck** [comment]
I confirm, #116 fixed all this stuff, i removed the ./messages ref, added the dirname and updated all the protos (see the changelog on the pull request for fulltime details. I suggest you add the pull to Your local repo and test it out. If it works, post an ack in the pull thread, we're waiting on confirmation to add it

**Comment by howardchung** [comment]
Breaking changes:
* Methods renamed: https://github.com/RJacksonm1/node-dota2/pull/90#issuecomment-139298698
* node-dota2 no longer converts snake_case to camelCase

TODO
- [ ] update README
- [x] matches
- [x] profiles

**Comment by howardchung** [comment]
We can try to set up automated testing with Travis CI, but we need to consider the rate limit.  Presumably we'll make one test account.  I don't know if the limit is 100 calls per type per day, or 100 total.  If it's the former we can probably be okay if we don't make too many commits at once.

**Comment by howardchung** [comment]
It seems like @RJacksonm1 already partially updated the README.

Automated testing would be nice but we don't have to do it before we push out a new npm version.

Anything blocking us from doing that now?

**Comment by howardchung** [comment]
I'd just say we should add a section for 1.0.0 breaking changes (I mentioned them above), and probably add profileCards to the API listing.

@Crazy-Duck, can you take care of it? :)

**Comment by Crazy-Duck** [comment]
I'll try and look into it during the weekend, shouldn't be too much of a hassle.

**Comment by howardchung** [comment]
Are we good to release?

Signoffs from everyone involved?

**Comment by jimmydorry** [comment]
In terms of open issues that are tagged with this milestone, we still have a few. If we can close or defer any of them, please signal so.

I'm not too fussed with the automated testing, as @RJacksonm1 (RFraudson) clearly has not delivered. :fist: 

https://github.com/RJacksonm1/node-dota2/milestones/1.0.0

**Comment by jimmydorry** [comment]
Sweet. I'll re-base and merge this tonight when I have access to my IDE and git. If someone can do it sooner, I'll merge that.

**Comment by Crazy-Duck** [comment]
@howardchung did you do any tests with node-steam 1.2.0 yet? If so I think we can bump the dependency to that one for our 1.0.0 version. In any case, the 1.0.0-dev branch has become much more stable than the master over the past few weeks, so it will be nice to have it up to date. One thing I am not so sure about though is the test.js example. Did any check this recently?

**Comment by Crazy-Duck** [comment]
I added a final pull request for the README. Going over the comments I saw I forgot to add the notice pertaining to the snake_case conversion.

**Comment by howardchung** [comment]
No, I haven't tested it with 1.2.0 yet.  You could try it if you have time (pretty quick, should be no API changes).

**Comment by Crazy-Duck** [comment]
Last commit updates the package.json to node-steam ^1.2.0. I think we're about ready for 1.0.0 now. Put the champagne in the fridge I'd say :D

**Comment by jimmydorry** [comment]
We did it guys!

**Comment by Crazy-Duck** [comment]
Hurraaaay!

**Comment by RJacksonm1** [comment]
Automated testing looked hard!

**Comment by RJacksonm1** [comment]
Tagged 1.0.0 and published on npm!  Good work valued open source contributors!

**Pull request closed without merging**
