### PR TITLE
Turn type proto message id into proto name

### PR DESCRIPTION
**Pull request by Crazy-Duck**
Very old feature request. When you activate additional debugging, the print-out will now show the name of the prototype instead of the ID.

### CODE REVIEW

**Comment by Crazy-Duck** [comment]
Just a time-out on the first steam connection for the node v6.* test, v4.* test ran fine

**Comment by howardchung** [comment]
If both tests run simultaneously one may fail since the steam account can only be logged in once.

**Comment by Crazy-Duck** [comment]
They run consecutively, it's just that the first connection to steam took a little more than 10s causing the test on the steam connection to time out. All subsequent funcitonality tests passed just fine

**Comment by howardchung** [comment]
We may want to increase timeout then to avoid test flakiness.

**Comment by Crazy-Duck** [comment]
We may yes :D however I don't know who has sufficient rights to make the adjustment. @jimmydorry do you know how we could add e.g. 5s to the timeout duration?

**Comment by howardchung** [comment]
It should just be a patch to the test.js file.  You can PR it yourself.

**Comment by Crazy-Duck** [comment]
derp, found it
```
this.timeout(10000); // 10s timeout because Steam is slooooooooow
```

**Pull request merged**
