### PR TITLE
Beautified (re-indented) js files

### PR DESCRIPTION
**Pull request by imayhaveborkedit**
Also changed `update_protos.sh` to use `#!/bin/bash` instead of sh

### CODE REVIEW

**Comment by jimmydorry** [comment]
looks like it is just beautifying, but will need to have a closer look on the weekend.

**Comment by Crazy-Duck** [comment]
Next thing you know we'll start having coding standards :D

**Comment by jimmydorry** [comment]
Nah, i bet this is for the hacktoberfest t-shirt that requires you to open four PRs. There couldn't possibly be any other reason to consider the whitespacing in a library. Kappa

**Comment by Crazy-Duck** [comment]
Oh wow I didn't even know that was a thing :D just subscribed, easy free tshirt ^^

**Comment by imayhaveborkedit** [comment]
Since there's a dev branch now i'll update this to go into that instead of master.

**Comment by jimmydorry** [comment]
Thanks, that makes more sense. :+1:

**Pull request closed without merging**
