### PR TITLE
Added coin flip and dice roll functions

### PR DESCRIPTION
**Pull request by Crazy-Duck**
Cause who doesn't like to gamble

### CODE REVIEW

**Comment by jimmydorry** [comment]
This is the most useful addition so far! Especially better than the tests. GreyFace

**Comment by Crazy-Duck** [comment]
Critical bug...? o_O

**Comment by jimmydorry** [comment]
Absolutely. No one even looks at the tags. :sob:

**Comment by imayhaveborkedit** [comment]
I do :disappointed:

**Comment by Crazy-Duck** [comment]
How can an enhancement be a critical bug? :laughing:

**Comment by jimmydorry** [comment]
Fine

**Comment by Crazy-Duck** [comment]
Seems like an adequate tag for the most useful addition so far ^^ FeelsGood

**Pull request merged**
