### PR TITLE
Badges, Badges everywhere

### PR DESCRIPTION
**Pull request by Crazy-Duck**
Because who doesn't love badges

### CODE REVIEW

**Comment by jimmydorry** [comment]
Who is David? I guess there is only one way to find out. SHIP IT, FUCK IT.

**Comment by Crazy-Duck** [comment]
David is a nice guy who will prevent @RJacksonm1 from forgetting to update his dev dependencies xD

**Comment by jimmydorry** [comment]
Not possible. I bet @RJacksonm1 feels smug when he sees lots of red badges telling him shit is fucked, or that he needs to do something.

**Comment by RJacksonm1** [comment]
Wut.  I never update anything.  I don't do any work on this project.

**Pull request merged**
