### PR TITLE
Beautified js files

### PR DESCRIPTION
**Pull request by imayhaveborkedit**
I redid these from the dev branch.  I can do these every once in a while if needed.  If you feel the need to test everything something something cough cough travis cough automated tests.

### CODE REVIEW

**Comment by jimmydorry** [comment]
I think I can fix the conflict. Will do the manual merge tonight.

**Comment by imayhaveborkedit** [comment]
Alright my brain can't figure out how to fix this.  I guess i'll leave it to you.

**Comment by howardchung** [comment]
lol@commit messages

**Comment by imayhaveborkedit** [comment]
This is when my brain's capacity to deal with git declines and devolves into spamming commits hoping one of them works.

**Comment by jimmydorry** [comment]
Simplest solution is to fork the dev branch. Copy over the files that don't conflict. Manually merge the chat.js that does conflict.

**Comment by imayhaveborkedit** [comment]
I DID IT

**Comment by jimmydorry** [comment]
I don't see any code changes.

**Comment by Crazy-Duck** [comment]
These commits are like a slow descent into madness right before a eureka moment :p

**Comment by jimmydorry** [comment]
Yea :(

**Pull request merged**
