### PR TITLE
Update region list and moved to helper

### PR DESCRIPTION
**Pull request by Crazy-Duck**
Nobody will suspect a thing
#218

### CODE REVIEW

**Comment by jimmydorry** [comment]
All according to keikaku.

TL Note: keikaku means plan

I now need to go find a new minor change to make sure I get the first commit in the dev branch. I think we are missing the config sample. Hehe :)

**Comment by Crazy-Duck** [comment]
thank god admin has his priorities straight :p

**Comment by jimmydorry** [comment]
:+1:

**Comment by Crazy-Duck** [comment]
Do you want me to make the same PR into the dev branch as well?

**Comment by jimmydorry** [comment]
Already done

**Comment by jimmydorry** [comment]
iOS capitalised it without me catching it though. I'll bring back the config sample tomorrow when I have a keyboard.

**Comment by Crazy-Duck** [comment]
are you reverting the capitalisation as well? Just so I don't need to re-link my local copies to the correct upstream :p

**Comment by RJacksonm1** [comment]
UNSUBSCRIBE

**Comment by jimmydorry** [comment]
Fine... Fixed. Pretty sure you still need to delete your local branches and re-pull origin (upstream).

**Comment by Crazy-Duck** [comment]
nah, just need to do a pull and delete the Dev remote branch

**Comment by mjxtw1989** [comment]
How to invite other people to join the game?

**Comment by jimmydorry** [comment]
Open a new issue @mjxtw1989 

The answer is to have a look at the readme. It's very explicitly explained there.

**Pull request merged**
