### PR TITLE
Refactoring according to #107

### PR DESCRIPTION
**Pull request by Crazy-Duck**
Alright, paging everyone to see if their stuff still works. 
@howardchung did I break yasp?
@imayhaveborkedit did I bork it?
@jimmydorry is it a classic jimmy?

### CODE REVIEW

**Comment by jimmydorry** [comment]
Looking sharp. Soo many lines removed!

**Comment by Crazy-Duck** [comment]
Yeah, it's pretty clean actually. It's become a lot more understandable for newcomers now as well. Only thing you need to do to implement a new proto message is just defining the payload, it's pretty neat.

**Comment by Crazy-Duck** [comment]
The only thing I'm wondering about is if we shouldn't invoke the callback with an error when GC isn't ready as well. Up until now we've always just returned null, so apart from a line in the logs and the fact the callback is never invoked, the user has little information on what's happening. Furthermore, because the callback is never invoked the user also has no way of acting upon the error... I don't know, what do you guys think?

**Comment by jimmydorry** [comment]
Callback it!

You could also just throw an error. Pretty hard to miss that. :+1:

**Comment by howardchung** [comment]
If we can merge in @RJacksonm1's automated tests they should be sufficient
to ensure no yasp breakage.

Also it wouldn't break unless I did a blind npm version bump--which I have
admittedly done before.

**Comment by imayhaveborkedit** [comment]
I don't think doing nothing when something breaks is a good way of handling things either.  I like knowing what broke and why.  I like the new changes though. @RJacksonm1 is going to have to update his blog now.

**Comment by RJacksonm1** [comment]
Oh god how do I do that.

**Comment by jimmydorry** [comment]
Just merge them in @RJacksonm1

**Comment by howardchung** [comment]
Callback, don't throw.  You don't want to crash the user's application.

**Comment by Crazy-Duck** [comment]
Trouble is, the callback we receive in the helper function is the modified one, i.e. If I call that one we arrive in the handlers. Those will freak out because the first thing they do is trying to parse the message, which will obviously fail... The only thing I can think of is changing the helper so it takes two optional arguments: the handler and the callback. That way we can call the original callback function when gc isn't ready and transform if it is...

**Comment by jimmydorry** [comment]
Shall we merge as is, and make an issue for further improvements?

**Comment by RJacksonm1** [comment]
Forgive me, I'm a little out of touch.

Am I correct in interpreting the problem as follows:

* On any error, we want to provide any user-provided callbacks (not our handlers) with an error.
* Our current mechanism passes user-provided callbacks via our handlers
* Our handlers are not set up to work without being passed a valid response (ergo we can't call the user-provided callbacks)

Does the callback returned from `convertCallback` get called, now that the GC ready check (and associated `return null` has been removed?  I'm guessing something gets passed there to let us know that a particular call failed?

I'm thinking we may be able write a function to verify the GC response, and have that function handle GC error cases for the callback.  Handlers can all use that function, and if the function returns false: The handler exits early.  Is something like that a feasible solution?

**Comment by Crazy-Duck** [comment]
For the moment if a call fails due to any reason _other_ than GC not ready, one of our handlers is called. Our handlers already know how to interpret the messages we receive from the GC, even when the GC returns an error (it doesn't make much sense to create a generic GC error handler, seeing as the business varies based on the call, furthermore, the problem isn't in the handling of the GC response). Subsequently, our handlers invoke the user-provided callbacks and pass them an error message. However, before a message is sent to the GC, our code does a check to see if the GC is ready. If it isn't, nothing happens and there is no feedback to the user; this is the behaviour we'd like to change. The way it's implemented now, we can't directly invoke the user-provided callback, because the one we receive as input to the helper function is a reference to one of our handlers. What I'm proposing is changing our helper function to the following (not yet tested):
```JavaScript
Dota2Client.prototype.sendToGC = function(type, payload, handler, callback) {
    if (!this._gcReady) {
        if (this.debug) util.log("GC not ready, please listen for the 'ready' event.");
        if (callback) callback(-1, null); // tbd what we return here
    } else {
        this._protoBufHeader.msg = type;
        this._gc.send(this._protoBufHeader, payload.toBuffer(), Dota2._convertCallback(handler, callback));
    }
}
```

**Comment by Crazy-Duck** [comment]
Alright, I changed the sendToGC so we now do a callback when GC isn't ready and I adjusted all payload constructors accordingly. Callback arguments are `-1, null`. I've done a few sanity checks and I didn't find anything broken, it seems to work as it should now.

**Comment by jimmydorry** [comment]
Alright! Let's merge it, and maybe give it a few days before the big merge and version increment in master.

**Pull request merged**
