### PR TITLE
add basic test for requestMatchDetails

### PR DESCRIPTION
**Pull request by howardchung**

### CODE REVIEW

**Comment by RJacksonm1** [comment]
Bother.

**Comment by RJacksonm1** [comment]
Oh wait this is a legit pull req too.  Wonder if the tests will run once I merge it! Lets find out!

**Comment by RJacksonm1** [comment]
shit I merged it and it didn't even work. whoops.

Send help!

https://travis-ci.org/RJacksonm1/node-dota2/builds/99670573

```
  1) Dota2 Matches #requestMatchDetails should fetch data on a given match id:
     Uncaught AssertionError: expected undefined to exist
      at test/test.js:222:28
      at Dota2Client.onMatchDetailsResponse (handlers/match.js:141:19)
      at Object.<anonymous> (handlers/match.js:84:42)
      at SteamGameCoordinator.handlers.(anonymous function) (node_modules/steam/lib/handlers/game_coordinator/index.js:105:28)
      at SteamGameCoordinator.<anonymous> (node_modules/steam/lib/handlers/game_coordinator/index.js:19:28)
      at SteamClient._netMsgReceived (node_modules/steam/lib/steam_client.js:172:10)
      at SteamClient.handlers.(anonymous function) (node_modules/steam/lib/steam_client.js:259:10)
      at SteamClient._netMsgReceived (node_modules/steam/lib/steam_client.js:157:26)
      at Connection._readPacket (node_modules/steam/lib/connection.js:50:8)
      at emitReadable_ (_stream_readable.js:411:10)
      at emitReadable (_stream_readable.js:405:7)
      at readableAddChunk (_stream_readable.js:157:11)
      at Connection.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)
```

**Comment by RJacksonm1** [comment]
Whew I solved it.  219e5729255da80c1ed73ce4f2a72f613662f6a7 I'm really good.

**Comment by Crazy-Duck** [comment]
And modest, kappa

On 1 Jan 2016 2:30 am, Rob Jackson <notifications@github.com> wrote:

Whew I solved it. 219e572 I'm really good.

**Pull request merged**
