### PR TITLE
protobufjs

### PR DESCRIPTION
**Pull request by howardchung**
@pyarmak updated node-dota2 to use protobufjs, which doesn't require the long build of protobuf.  YASP has been using the changes in production for a few months now (although we only use match details and player profile requests).

I'm sharing those changes in this PR, but it will require some manual merging since node-dota2 has updated since the changes were made.

### CODE REVIEW

**Comment by pyarmak** [comment]
+1 on this.
I totally forgot to make this PR.

**Comment by jimmydorry** [comment]
Thanks for the hard work, and sorry I didn't get to it sooner. These changes should be included in the mega pull. If not, please make them again once it has been merged.

**Comment by Crazy-Duck** [comment]
Since I started mega pull #90 based on this revision, this shouldn't be a problem :)

**Comment by jimmydorry** [comment]
;)

**Comment by pyarmak** [comment]
I've been away and busy for the past while (this should be my last week of madness though!).
Just dropped by to say awesome work everyone. I'm glad this is getting done.

**Pull request closed without merging**
