### PR TITLE
Refactor to address GC not ready code duplication

### PR DESCRIPTION
**Pull request by devilesk**
As suggested in issue https://github.com/RJacksonm1/node-dota2/issues/107 I added a helper function and then updated all the handlers to use them.

I've only done one quick test so far which is logging a bot on and it was able to join a channel without a problem. Haven't done a test showing the actual log, but the change is trivial so I don't see why it wouldn't work. EDIT: Ran a test setting _gcReady to false and it logged properly.

### CODE REVIEW

**Comment by jimmydorry** [comment]
Thanks, waiting for ACK from @paralin

**Comment by RJacksonm1** [comment]
I don't think this solves much at all, it just moves where the 'util.log' statement resides. All of our GC interfacing code all boil down to doing 2 things: Building a payload, sending that payload to the GC (with the relevant type); so I think we can improve this by replacing the ` this._client.toGC` with a custom method, e.g. `this.sendToGC(type, payload, [callback])`; this function can do the GC ready check, as well as abstract away some of the other "noise" that our methods don't really need to concern themselves with.

For example, instead of having:

```
Dota2.Dota2Client.prototype.joinChat = function(channel, type) {
  type = type || Dota2.DOTAChatChannelType_t.DOTAChannelType_Custom;

  /* Attempts to join a chat channel.  Expect k_EMsgGCJoinChatChannelResponse from GC */
  if (!this._gcReady) {
    if (this.debug) util.log("GC not ready, please listen for the 'ready' event.");
    return null;
  }

  if (this.debug) util.log("Joining chat channel: " + channel);
  var payload = dota_gcmessages_client.CMsgDOTAJoinChatChannel.serialize({
    "channelName": channel,
    "channelType": type
  });

  this._client.toGC(this._appid, (Dota2.EDOTAGCMsg.k_EMsgGCJoinChatChannel | protoMask), payload);
};
```

We could refactor things so we only need:

```
Dota2.Dota2Client.prototype.joinChat = function(channel, type) {
  type = type || Dota2.DOTAChatChannelType_t.DOTAChannelType_Custom;

  if (this.debug) util.log("Joining chat channel: " + channel);
  var payload = dota_gcmessages_client.CMsgDOTAJoinChatChannel.serialize({
    "channelName": channel,
    "channelType": type
  });

  this.sendToGC(Dota2.EDOTAGCMsg.k_EMsgGCJoinChatChannel, payload);
};
```

So we abstract away the GC ready check, the passing of appid, and the bitwise OR with proto type and protomask.  In this example it doesn't clear up a lot, but it would reduce a lot of duplication across the whole library.

This is something I was going to look into when I next have time to work on the library, but I'm more than happy if anybody else wants to take on this refactoring work.  That's assuming there are no glaring problems with this approach that I haven't identified.

**Comment by paralin** [comment]
I agree with Rob, there's a lot more simplification possible here.

**Comment by jimmydorry** [comment]
Superseded by https://github.com/RJacksonm1/node-dota2/issues/110

**Pull request closed without merging**
