### PR TITLE
Proto update + fix matchminimal test

### PR DESCRIPTION
**Pull request by Crazy-Duck**
I checked all proto changes, apart from winning_team nothing breaking changed

### CODE REVIEW

**Comment by Crazy-Duck** [comment]
Btw, @jimmydorry do you prefer me committing straight into staging and then making the pull into dev, or would you rather I create another branch and pull into staging?

**Comment by jimmydorry** [comment]
I think it would be better to make your own crazy-duck branch, and pull into dev from there. You have the power to merge when you see it passes travis, so no need to wait for me either.

**Comment by jimmydorry** [comment]
It passed, that's so dope.

**Comment by Crazy-Duck** [comment]
Alright, next time I make changes i'll make a separate branch then

**Pull request merged**
