### PR TITLE
Update protobufs

### PR DESCRIPTION
**Pull request by jimmydorry**
@Crazy-Duck Let's have a look at what updated.

Of note:

- CMsgPlayerConductScorecardRequest
- Wagering stuff
- 3 new combat log entries (BOTTLE_HEAL_ALLY, ENDGAME_STATS, INTERRUPT_CHANNEL)
- They really hate people that track things, re-using event IDs like that (EVENT_ID_WINTER_MAJOR_2016)

And... literally nothing else.

### CODE REVIEW

**Comment by Crazy-Duck** [comment]
welp, must've missed that protomessage when implementing the lobby stuff

**Comment by jimmydorry** [comment]
Yea, matchIDs are supposedly 64bit unsigned now. Legacy apps should feel the crunch soon.

**Comment by howardchung** [comment]
Getting close:
https://yasp.co/status

2139021365/2147483647

**Comment by jimmydorry** [comment]
GreyFace

I'm sure that responsible developers have already accounted for 32bit matchID crunch. Fine developers like @manveru

**Pull request merged**
