### PR TITLE
Update lobbies.js

### PR DESCRIPTION
**Pull request by XenBG**
Added variables in createPracticeLobby.

### CODE REVIEW

**Comment by jimmydorry** [comment]
Thanks for the hard work, and sorry I didn't get to it sooner. These changes will need to be included in the mega pull https://github.com/RJacksonm1/node-dota2/pull/90 when it's merged.

**Comment by Crazy-Duck** [comment]
I'm actually not convinced about this one... functions with this many input arguments are generally considered bad practice, as they become very unwieldy. More-so since there already exists a function which allows you to configure the practice lobby, which takes all these arguments as a map. I'd keep the create function as simple as possible and have it take just enough arguments to actually create the lobby. The configure function can then be used to set all possible options

**Comment by RJacksonm1** [comment]
I agree with @Crazy-Duck on the points of having a massive function signature, but I think we should allow users to create the lobby with given set of options. There's little point forcing two calls to the GC if only one will suffice.

I suggest having all of the necessary parameters for creating a lobby to be required in the function signature, and accepting an optional "options" parameter for any extra options.

We can extract the logic in `configPracticeLobby` relating to possible options into a dedicated function, update it (this PR is adding new options that `configPracticeLobby` doesn't handle, for example `league_id`, `game_version`), and re-use it for both `createPracticeLobby` and `configPracticeLobby`.

Sound good?

**Comment by XenBG** [comment]
Yes, you are right, guys.

**Comment by jimmydorry** [comment]
Rebase and pull into the steam1.1.0 branch, after considering what our glorious leader (rjackson) has suggested. Thanks for your consideration.

https://github.com/RJacksonm1/node-dota2/tree/node-steam1.1.0

**Pull request closed without merging**
