### PR TITLE
New tests, proto updates, README fix, deprecated functions

### PR DESCRIPTION
**Pull request by Crazy-Duck**
Mocha results:
  17 passing (14s)
  28 pending

We're 1/3rd of the way

### CODE REVIEW

**Comment by jimmydorry** [comment]
Do we need to change our workflow, and instead have all PRs go into a different branch, and then I PR into dev, so we can see if it works via Travis?

All the PRs have had eresult 5, which is invalid password. I assume that this is because it will only use environment variables on PRs from members of the repo.

**Comment by Crazy-Duck** [comment]
Yeah, Howard has explained this before, it's to prevent unknown members from making pulls printing the credentials. I'd keep the dev branch as it is, but rather make a staging branch. That way people can keep committing in dev like they're used to, and you can pull into staging to see if they pass

**Comment by howardchung** [comment]
Or if you trust @Crazy-Duck , you can make him a collaborator :)

**Comment by Crazy-Duck** [comment]
which wouldn't solve anything for all the other collaborators :p

**Comment by jimmydorry** [comment]
I would, but I have no power unfortunately. >_<

I would have done it ages ago. :+1:

**Pull request merged**
