### PR TITLE
Update all dependencies 🌴

### PR DESCRIPTION
**Pull request by paralin**
Tests pass. 

https://travis-ci.org/paralin/node-dota2/builds/151424420

### CODE REVIEW

**Comment by paralin** [comment]
Will send to `dev` instead.

**Comment by jimmydorry** [comment]
Send to staging actually @paralin

**Comment by paralin** [comment]
@jimmydorry Can you set the default PR branch to "staging"

And while you're at it if you want you should enable "greenkeeper" on your repo, I've done it on my fork and will send PRs but if you do it directly it'd be better.

**Comment by jimmydorry** [comment]
I don't have access to any of the settings. @RJacksonm1 pls

**Comment by jimmydorry** [comment]
@Crazy-Duck wow, that "greenkeeper" looks cool. Do we want it?

https://github.com/paralin/node-dota2/pull/2

**Comment by paralin** [comment]
Have a look at the kind of stuff it does: https://github.com/emilebres/react-flex-accordion/pull/9

**Comment by paralin** [comment]
It's pretty awesome because it will actually let you know exactly when dependencies update (so you can track without falling outdated) and lets you know if the update breaks the build or not.

**Comment by Crazy-Duck** [comment]
drool

**Comment by RJacksonm1** [comment]
Default branch changed. Can't see any setting to do with greenkeeper.

**Comment by RJacksonm1** [comment]
Also moved repo to Arcana and invited @jimmydorry and @Crazy-Duck to the Arcana "Dota" team, which will give you guys admin level access to this repository.

**Comment by paralin** [comment]
The default branch setting changes which branch Greenkeeper watches

**Comment by jimmydorry** [comment]
I'm an arcana now. I would just like to take a minute to thank the community for voting for me. I promise to do more good than wisp bro.

Also @RJacksonm1 how much stuff will the URL change break? Does npm still work? :fire:

**Comment by RJacksonm1** [comment]
GitHub told me nothing will break. Let's see if it's lying.

**Comment by Crazy-Duck** [comment]
The cake is a lie! Seems like our travis badge in the README broke. Shame on GitHub for not automatically creating a PR to update the link []()

**Comment by paralin** [comment]
Not just the badge broke, you'll need to activate Travis for the new repo
too

**Pull request closed without merging**
