### PR TITLE
Implement lobby invitation request

### LINKED ISSUE #71: Lobby invite implementation
There are new protos in place now for lobby invites. Need to implement these.

### PR DESCRIPTION
**Pull request by paralin**
Barely tested, but should work. The GC sends a `CMsgInvitationCreated` which I'm not quite sure how to handle with the callbacks. But, it's not really important. There's very little state info provided about invitations to lobbies, so this is the best I can do for now.

Fixes #71

### CODE REVIEW

**Comment by jimmydorry** [comment]
Waiting for an ACK before merging.

**Comment by jimmydorry** [comment]
Where'd this go? I lost track of it.

**Comment by paralin** [comment]
I don't know, I think it was re-implemented in the 1.0 branch

**Comment by Crazy-Duck** [comment]
I don't think so, this hasn't been merged yet (at least I don't find anything on the 1.0.0-dev branch). Can you recreate the pull?

**Comment by Crazy-Duck** [comment]
I made a new pull with this code. I left out the callback since it didn't seem to do anything on my end. @paralin did you get that one working?

**Pull request closed without merging**
