### PR TITLE
Bump 4.0.0

### PR DESCRIPTION
**Pull request by Crazy-Duck**
Protobuf fixes + version update since new incompatibilities.

It sucks pretty hard that team lookups have been sacked by Valve (in any case I can't find a single trace of them in the protobufs anymore). RIP my team registration bot :'(

### CODE REVIEW

**Comment by Crazy-Duck** [comment]
Hmm, seems like travis still isn't entirely happy... 
@howardchung if I recall correctly, we implemented the tests in mocha right? I suppose we need to modify the package.json to launch them with mocha then? What's needed in terms of devDependencies? I've added should, but do we need to add describe and mocha as well?

**Comment by howardchung** [comment]
https://travis-ci.org/RJacksonm1/node-dota2/jobs/133924468

Do `npm install --save-dev mocha`

**Comment by Crazy-Duck** [comment]
mocha tests now run locally, fingers crossed for travis

**Comment by Crazy-Duck** [comment]
Alright, Travis still seems to be failing, even though everything works locally. Am I correct in assuming the logon parameters might be missing?

**Comment by howardchung** [comment]
Travis will not set the environment variables on external pull requests (to previous a malicious user dumping them in the log)

**Comment by Crazy-Duck** [comment]
Derp, forgot all about that, this should be ok for merge then

**Comment by jimmydorry** [comment]
Cool, let's fire and forget!

**Pull request merged**
