### PR TITLE
Fixed an issue with camel casing being replaced with underscores.

### PR DESCRIPTION
**Pull request by macnibblet**

### CODE REVIEW

**Comment by jimmydorry** [comment]
@howardchung @Crazy-Duck

**Comment by howardchung** [comment]
I've never used this so no idea how to test

**Comment by jimmydorry** [comment]
Did we change from camel, everywhere else?

**Comment by jimmydorry** [comment]
Did we change from camel, everywhere else? If it's a consistency thing, then that makes sense.

**Comment by howardchung** [comment]
yes, we should have.

**Comment by jimmydorry** [comment]
Fuck it. Ship it.

**Comment by Crazy-Duck** [comment]
It's not a consistency thing, but an actual bug. The multi variable is a proto construct, so should be in snake-case since the switch to node-steam 1.x.x. We must've missed this one when refactoring, good catch

**Comment by jimmydorry** [comment]
Thanks for the confirm

**Comment by macnibblet** [comment]
Ill doing some larger pull requests later, but how on earth do one actually test this in a reasonable fashion ?

**Comment by Crazy-Duck** [comment]
Automated testing is on the roadmap, but not implemented yet. For now, everyone just checks if their stuff still works with the changes. Most of the time I additionally randomly select some functions left and right and see if they still work. Once a couple of regulars confirm stuff still works it gets merged.

**Comment by macnibblet** [comment]
@Crazy-Duck Any chance we could write a cleanup for the 1.0.0-dev to use promises instead of callbacks ?

**Comment by Crazy-Duck** [comment]
I moved this discussion to an issue, makes it easier to talk about instead of having to keep commenting on a closed pull

**Pull request merged**
