### PR TITLE
* Adding basic support for CMsgPracticeLobbyJoinBroadcastChannel. The…

### PR DESCRIPTION
**Pull request by tomasmck**
…re are additional options for this GC Request which haven't been implemented here. This provides the default functionality.

* Updated README.

### CODE REVIEW

**Comment by jimmydorry** [comment]
Great work, but you need to PR into the dev branch. https://github.com/RJacksonm1/node-dota2/tree/dev

People would get mighty cross if MASTER ever broke.

Also, for the sake of aesthetics, can you match the formatting of the surrounding code?

I'm going to close this PR.

:+1:

**Comment by tomasmck** [comment]
Thanks @jimmydorry. I'll do this now.

Are there examples of existing tests?

**Comment by jimmydorry** [comment]
There sure are, but it's black magic to me.

https://github.com/RJacksonm1/node-dota2/blob/automated-testing/test/test.js

In the dev branch, we have renamed test.js to example.js, so if you are going to make a PR that introduces new tests, make sure to add a test.js file. 

I'll merge it into our `automated testing` branch later.

**Comment by jimmydorry** [comment]
https://github.com/RJacksonm1/node-dota2/blob/automated-testing/test/test.js#L59

Just a note, the current `automated tests` use environment variables. So you may need to modify it slightly to get it running locally.

**Pull request closed without merging**
