### PR TITLE
Updated matchmakingStatsData and readme

### PR DESCRIPTION
**Pull request by imayhaveborkedit**
#165

### CODE REVIEW

**Comment by jimmydorry** [comment]
- Match group not ordered
- rename the events in the readme to match the changes made in the handler
- add a note near the top of readme to indicate your breaking change
- and please squash to a single commit... or redo commits so they reflect actual changes

Thanks

**Comment by Crazy-Duck** [comment]
also, in the readme part, if `disabledGroups` were a bitmask, the group numbers would go up with powers of two. The bitmask comment in your issue post was just a suggestion, we might need to play around with it some more to find out what exactly it is. @paralin do you have this function implemented in your c# code base yet? If so, anything to add as to how this parameter should be interpreted?

**Comment by paralin** [comment]
@Crazy-Duck I wasn't aware there was anything updated here. I'll have to look at it tonight.

**Comment by imayhaveborkedit** [comment]
I'm resetting my dev branch because git is hard.

**Pull request closed without merging**
