### PR TITLE
Update README + fix small bug in example2.js

### PR DESCRIPTION
**Pull request by jimmydorry**
The test pull for https://github.com/RJacksonm1/node-dota2/pull/297

### CODE REVIEW

**Comment by jimmydorry** [comment]
@Crazy-Duck 

			  2) Dota2 Matches #requestMatchMinimalDetails should fetch a list of minimal match data corresponding to the given ids:
				 Uncaught AssertionError: expected null to exist
				  at test/test.js:244:14
				  at Dota2Client.onMatchMinimalDetailsResponse (handlers/match.js:136:23)
				  at Object.<anonymous> (handlers/helper.js:118:21)
				  at SteamGameCoordinator.handlers.(anonymous function) (node_modules/steam/lib/handlers/game_coordinator/index.js:105:28)
				  at SteamGameCoordinator.<anonymous> (node_modules/steam/lib/handlers/game_coordinator/index.js:19:28)
				  at SteamClient._netMsgReceived (node_modules/steam/lib/steam_client.js:172:10)
				  at SteamClient.handlers.(anonymous function) (node_modules/steam/lib/steam_client.js:259:10)
				  at SteamClient._netMsgReceived (node_modules/steam/lib/steam_client.js:157:26)
				  at Connection._readPacket (node_modules/steam/lib/connection.js:50:8)
				  at emitReadable_ (_stream_readable.js:419:10)
				  at emitReadable (_stream_readable.js:413:7)
				  at readableAddChunk (_stream_readable.js:164:13)
				  at Connection.Readable.push (_stream_readable.js:111:10)
				  at TCP.onread (net.js:531:20)

**Comment by Crazy-Duck** [comment]
WutFace O_O I didn't even touch that stuff.. For one reason or another the winning_team field has become null... -_-'

**Comment by jimmydorry** [comment]
I did read recently, that Valve has been mucking around with winning_team for the webAPI, which broke Yasp and Dotabuff. They reverted it though, but maybe they have kept this "functionality" for the client. When the GC goes down, matches that finish don't have a winning result and either get a NULL, or the field is not set.

**Comment by Crazy-Duck** [comment]
nope, they yanked winning_team. I've just finished pulling the new protobufs and the signature has changed. Seems like our test correctly identified the library needs updating :D 
```
message CMsgDOTAMatchMinimal {
	message Player {
		optional uint32 account_id = 1;
		optional uint32 hero_id = 2;
		optional uint32 kills = 3;
		optional uint32 deaths = 4;
		optional uint32 assists = 5;
		repeated uint32 items = 6;
		optional uint32 player_slot = 7;
	}

	message League {
		optional uint32 league_id = 1;
		optional uint32 radiant_team_id = 2;
		optional string radiant_team_name = 3;
		optional fixed64 radiant_team_logo = 4;
		optional uint32 dire_team_id = 5;
		optional string dire_team_name = 6;
		optional fixed64 dire_team_logo = 7;
		optional uint32 series_type = 8;
		optional uint32 series_game = 9;
	}

	optional uint64 match_id = 1;
	optional fixed32 start_time = 2;
	optional uint32 duration = 3;
	optional .DOTA_GameMode game_mode = 4 [default = DOTA_GAMEMODE_NONE];
	repeated .CMsgDOTAMatchMinimal.Player players = 6;
	optional .CMsgDOTAMatchMinimal.League league = 7;
	optional .EMatchOutcome match_outcome = 8 [default = k_EMatchOutcome_Unknown];
}
```

**Pull request merged**
