### PR TITLE
Unification of method, event and handler naming conventions

### PR DESCRIPTION
**Pull request by Crazy-Duck**
My proposition for name changes, basically the gist of it is that all methods which aim to obtain a certain piece of information from the GC become "requestSomething" and all handler methods become "onSomethingResponse". The corresponding events which are thrown become "somethingData". A lot of the methods/handlers/events already followed this syntax, I just aimed to make this a uniform standard throughout the API. I've got the commit ready, if you guys agree, I'll add it to the PR. 
Number of breaking changes: 8 events + 10 methods

### chat.js
|Old|New|
|---|---|
|onRequestChatChannelListResponse|onChatChannelsResponse|
|this.emit('chatChannelsReceived', channels)|this.emit('chatChannelData', channels)|
### community.js
|Old|New|
|---|---|
|getPlayerMatchHistory|requestPlayerMatchHistory|
|profileRequest|requestProfile|
|passportDataRequest|requestPassportData|
|hallOfFameRequest|requestHallOfFame|
### guild.js
|Old|New|
|---|---|
|onGuildData|onGuildDataResponse|
|this.emit("guildInvite", ...)|this.emit("guildInviteData", ...)|
### leagues.js
|Old|New|
|---|---|
|leaguesInMonthRequest|requestLeaguesInMonth|
|onResponseLeagueInfo|onLeagueInfoResponse|
|this.emit("leaguesInMonthResponse", ...)|this.emit("leaguesInMonthData", ...)|
|this.emit("leagueInfo", ...)|this.emit("leagueInfoData", ..)|
### lobbies.js
|Old|New|
|---|---|
|practiceLobbyListRequest|requestPracticeLobbyList|
|friendPracticeLobbyListRequest|requestFriendPracticeLobbyList|
|this.emit("practiceLobbyListResponse", ...)|this.emit("practiceLobbyListData", ...) |
|this.emit("friendPracticeLobbyListResponse", ...)|this.emit("friendPracticeLobbyListData", ...)|
### match.js
|Old|New|
|---|---|
|matchDetailsRequest|requestMatchDetails|
|matchmakingStatsRequest|requestMatchmakingStats|
|onRequestMatchesResponse|onMatchesResponse|
|this.emit("matches", ...)|this.emit("matchesData", ...)|
|this.emit("matchData", ...)|this.emit("matchDetailsData", ...)|
### sourceTV.js
|Old|New|
|---|---|
|findSourceTVGames|requestSourceTVGames|
|nothing|this.emit("sourceTVGamesData", ...|

### CODE REVIEW

**Comment by RJacksonm1** [comment]
Renames make sense to me.  I'm happy for this to be merged, though I'd like to wait for more input before merging it myself.

**Comment by Crazy-Duck** [comment]
yeah, same here, especially since this modifies the api of a few of the more commonly used methods (match/community). @howardchung I know yasp uses some of these methods, would this change have a heavy impact on your code?

**Comment by howardchung** [comment]
We only use match details and player profiles.  So it would only be a two
line code change.  I'm fine with that.

**Comment by howardchung** [comment]
Any reason you want to use `*Data` for events and `*Response` for the function names?  Why not just `*Response` for both?

**Comment by Crazy-Duck** [comment]
The client receives a response, which contains the requested data. But honestly, it's more a mix of convenience (laziness) and not wanting to break all too much; a lot of the handler methods already had the response/data syntax.

**Comment by RJacksonm1** [comment]
Merged into new `1.0.0-dev` branch.

**Pull request closed without merging**
