### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Crazy-Duck**
Giving the good example **_\*cough\*_** hint **_\*cough\*_**

I did some basic sanity tests, seems they didn't break anything we use.
- protobuf.js -> just some internal naming stuff, npm package is compatible with 4.x.x
- bignumber.js -> minor bugfixes, all compatible

### CODE REVIEW

**Comment by jimmydorry** [comment]
Things didn't work out well, last time we allowed ranges. Why not give it an explicit version?

**Comment by Crazy-Duck** [comment]
For which one? I only changed the two, the others already specified a range.. Aren't minor updates not supposed to keep compatibility? Furthermore if I pin these versions, I'll probably have to redo this commit like every week or so, seems like protobuf updates quite regularily

**Comment by jimmydorry** [comment]
Big numbers has done breaking changes in the past. Would you even want to always be bleeding edge? Surely you just want a known and working configuration, and only do major updates every now and again?

**Comment by Crazy-Duck** [comment]
Did not know that about bignumber. However, I agree with the fact to only do major updates every now and again, but that's why I put the ^x.x.x to begin with. That modifier is supposed to exclude all major updates and only take the minor ones into account... Do I replace them with ~ to limit updates to bugfix?

**Comment by jimmydorry** [comment]
Meh, I guess the worst that will happen is people complain when it breaks. I just don't trust big numbers after it breaking compatibility last time. Same for node-steam, but that one was a more obvious break.

**Comment by Crazy-Duck** [comment]
Node-steam broke when going from 1.x.x to 2.x.x, so that was completely justified actually (same thing we did between 0.x.x and 1.x.x) ;)

**Comment by jimmydorry** [comment]
Yep :)

**Pull request merged**
