### PR TITLE
Version 3.0.0 release

### PR DESCRIPTION
**Pull request by jimmydorry**
Refer to the readme for breaking changes.

Once again, almost the entirety of this version was done by @Crazy-Duck

### CODE REVIEW

**Comment by jimmydorry** [comment]
@RJacksonm1 when this is merged (maybe an hour from now), please release on NPM.

**Comment by jimmydorry** [comment]
Oops, forgot to check back after it got tested.

**Comment by aios** [comment]
Update docs :+1:

**Comment by jimmydorry** [comment]
Docs should be up to date.

**Comment by RJacksonm1** [comment]
"reactions", kek

**Comment by jimmydorry** [comment]
:-1:

**Pull request merged**
