### PR TITLE
Readme additions + bugfix in example2

### PR DESCRIPTION
**Pull request by Crazy-Duck**
Rearranged the README a bit for better readability for first time users of the library. Relevant information for setting things up is now at the top. It also appears that the reference to node-dota2 in example2.js was borked, so I fixed that as well

### CODE REVIEW

**Comment by jimmydorry** [comment]
Why doesn't Travis work for your pulls, now you are a collaborator? :whale2:

**Comment by howardchung** [comment]
@Crazy-Duck may need to make his commit on a new branch in node-dota2.

https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables

**Comment by jimmydorry** [comment]
"Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code."

Make sense.

**Comment by Crazy-Duck** [comment]
oh ok, so instead of pulling from my fork, commiting straight to the staging branch on node-dota2 then?

**Comment by jimmydorry** [comment]
Yea! Or make your own branch you commit to, and PR from that branch. As a contributer, you can be working from this main repo instead of your fork.

**Pull request merged**
