### PR TITLE
2.0.0 Call for Release Candidate

### PR DESCRIPTION
**Pull request by jimmydorry**
We have quite a few small bug fixes and nice functionality enhancements. Time to consider merging them.

There are only two changes that are not backwards compatible.

* The `chatJoin` and `chatLeave` events were changed to return the channel name instead of the id. All debug logs pertaining chat channels will now mention chat channel instead of IDs.
* The `waitTimesByGroup` argument in the `matchmakingStatsData` event has been removed.

I'm open to bumping this to a new major version, as a result of the incompatibilities. (Need to update readme if we don't)

### CODE REVIEW

**Comment by Crazy-Duck** [comment]
I'm pretty much ok with bumping this to 2.0.0

**Comment by jimmydorry** [comment]
Okay, I will look at rolling this out into a release candidate branch this weekend.

It can then sit in the release candidate branch for a week or two, before hitting master.

- [ ] Rebase and merge into new v2.0.0 Release Candidate branch
- [ ] Close dev branch and re-branch it from Release Candidate branch
- [ ] Wait a week for feedback and last minute changes
- [ ] Push into master
- [ ] Ping @RJacksonm1 so he can do the magic, like pushing to npm, and figuring out why the tests explode..
- [ ] Celebrate

**Comment by jimmydorry** [comment]
Beeb boop, I am not a robot but I want to merge this this week. 

All against this merge, say I.

**Comment by Crazy-Duck** [comment]
I'm trying to figure out lobby invites at the moment and I've found a bug in cache.js (destroy ESOMsg ID is incorrect). I'll do my best to get a fix out before newyears.

**Comment by jimmydorry** [comment]
No worries. It can wait a week or so.

**Comment by Crazy-Duck** [comment]
This should be it I think, if there are no objections I guess we can ship 2.0.0 for newyears :)

**Comment by jimmydorry** [comment]
Roger, I think it's a pretty messy merge... but I can work through it tomorrow. :+1:

**Comment by twisterghost** [comment]
What the story on this? I'm running into the issue with party responses being broken, but there hasn't been a release beyond 1.0.1

**Comment by Crazy-Duck** [comment]
We're waiting for @jimmydorry to find some time to do the merge into the master. Mind, this is a pretty huge merge (lots of conflicts due to major internal restructuring) so this takes some time...

**Comment by twisterghost** [comment]
Understandable for sure. Looking forward to it :+1:

**Comment by jimmydorry** [comment]
Superseded by https://github.com/RJacksonm1/node-dota2/pull/215

**Pull request closed without merging**
